import type { Employee } from '../types';

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    position: 'Software Engineer',
    department: 'Engineering',
    status: 'active',
    joinedDate: '2023-01-15',
    avatarUrl: 'https://i.pravatar.cc/150?u=1',
    phone: '+1 555-0101',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    position: 'Product Manager',
    department: 'Product',
    status: 'active',
    joinedDate: '2022-11-01',
    avatarUrl: 'https://i.pravatar.cc/150?u=2',
    phone: '+1 555-0102',
  },
  {
    id: 3,
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice.j@example.com',
    position: 'UX Designer',
    department: 'Design',
    status: 'on_leave',
    joinedDate: '2023-03-10',
    avatarUrl: 'https://i.pravatar.cc/150?u=3',
    phone: '+1 555-0103',
  },
  {
    id: 4,
    firstName: 'Bob',
    lastName: 'Williams',
    email: 'bob.w@example.com',
    position: 'DevOps Engineer',
    department: 'Engineering',
    status: 'inactive',
    joinedDate: '2021-08-20',
    phone: '+1 555-0104',
  },
  {
    id: 5,
    firstName: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.b@example.com',
    position: 'Marketing Specialist',
    department: 'Marketing',
    status: 'active',
    joinedDate: '2023-06-01',
    avatarUrl: 'https://i.pravatar.cc/150?u=5',
  },
];
